default_stages: [commit, push]

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck

- repo: https://github.com/jsh9/pydoclint
  rev: 0.7.3
  hooks:
    - id: pydoclint
      args: [--style=google, --check-return-types=False]
